name: event_scanner_app
description: A Flutter scanner app skeleton for event tickets
publish_to: 'none' # for private project

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.0.5

  # HTTP client for API requests
  dio: ^5.9.1

  # QR Scanner
  mobile_scanner: ^3.0.0
  jsqr: ^0.1.3

  # Optional UI helpers
  cupertino_icons: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Lexend
      fonts:
        - asset: assets/Lexend-VariableFont_wght.ttf
  assets:
    - assets/voltraLogo.png